# Generated by Django 2.2.12 on 2020-06-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动的用户ID')),
                ('sid', models.IntegerField(verbose_name='被滑动的ID')),
                ('stype', models.CharField(choices=[('like', '喜歡'), ('superlike', '超级喜欢'), ('dislike', '不喜欢')], max_length=10, verbose_name='滑動窗口的記錄類型')),
                ('stime', models.DateField(auto_now_add=True, verbose_name='滑动时时间')),
            ],
        ),
    ]
